db.host=${DB_HOST:database}
db.port=${DB_PORT:3306}
db.name=${DB_NAME:holtun_db}
db.user=${DB_USER:holtun_user}
db.pass=${DB_PASS:holtun_pass}

spring.jpa.show-sql=false

server.port=8080

file.upload-dir=/app/uploads

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

logging.level.holtun.backend=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN

logging.file.name=/app/logs/app.log