db.host=localhost
db.port=3306
db.name=holtun
db.user=root
db.pass=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8088

file.upload-dir=./uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.resolve-lazily=false

server.tomcat.max-http-form-post-size=-1
server.tomcat.max-parameter-count=5000
server.tomcat.max-swallow-size=-1

logging.level.holtun.backend=DEBUG
logging.level.org.springframework.web=DEBUG